---
services:
  ntfy:
    image: binwiederhier/ntfy:v2.13
    container_name: ntfy
    command:
      - serve
    restart: unless-stopped
    volumes:
      - ./cache:/var/cache/ntfy
      - ./server.yml:/etc/ntfy/server.yml
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.ntfy.loadbalancer.server.port=80"
      - "traefik.http.routers.ntfy.rule=Host(`ntfy.local.lariscy.xyz`)"
      - "traefik.http.routers.ntfy.entrypoints=websecure"
      - "traefik.http.routers.ntfy.tls=true"
      - "traefik.http.routers.ntfy.tls.certresolver=leresolver"
    networks:
      - proxy

networks:
  proxy:
    external: true