---
services:
  wireguard:
    image: linuxserver/wireguard:arm64v8-1.0.20210914
    container_name: wireguard
    restart: unless-stopped
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules:ro
    ports:
      - "51820:51820/udp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
    env_file:
      - .env
    environment:
      - TZ=America/New_York
