---
services:
  mysql:
    image: mysql:8.4.6
    container_name: mysql
    restart: unless-stopped
    volumes:
        - ./data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - proxy
  
  phpmyadmin:
    image: phpmyadmin:5.2.2-apache
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - proxy
  
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: custom-php:8.4-apache
    container_name: php
    restart: unless-stopped
    volumes:
      - ./html:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.cef.loadbalancer.server.port=80"
      - "traefik.http.routers.cef.rule=Host(`cef.lariscy.xyz`)"
      - "traefik.http.routers.cef.entrypoints=websecure"
      - "traefik.http.routers.cef.tls=true"
      - "traefik.http.routers.cef.tls.certresolver=leresolver"
    depends_on:
      - mysql
    networks:
      - proxy

networks:
  proxy:
    external: true