---
services:
  mysql:
    image: mysql:8.4.6
    container_name: mysql
    restart: unless-stopped
    volumes:
        - ./data:/var/lib/mysql
    env_file:
      - .env
  
  phpmyadmin:
    image: phpmyadmin:5.2.2-apache
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
    ports:
      - "8080:80"
    depends_on:
      - mysql