http:
  middlewares:
    internal-only:
      ipAllowList:
        sourceRange:
          - 127.0.0.1/32
          - 192.168.86.0/24
        ipStrategy:
          excludedIPs:
            - 192.168.86.1 