---
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.0.1
    container_name: mealie
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - ./data:/app/data/
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.mealie.loadbalancer.server.port=9000"
      - "traefik.http.routers.mealie.rule=Host(`mealie.lariscy.xyz`)"
      - "traefik.http.routers.mealie.entrypoints=websecure"
      - "traefik.http.routers.mealie.tls=true"
      - "traefik.http.routers.mealie.tls.certresolver=leresolver"
    environment:
      ALLOW_SIGNUP: "false"
      TZ: America/New_York
      BASE_URL: https://mealie.lariscy.xyz
    networks:
      - proxy

networks:
  proxy:
    external: true