---
services:
  dockge:
    image: louislam/dockge:1
    container_name: dockge
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/app/data
      - /opt/homelab/docker:/opt/stacks
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.dockge.loadbalancer.server.port=5001"
      - "traefik.http.routers.dockge.rule=Host(`dockge.local.lariscy.xyz`)"
      - "traefik.http.routers.dockge.entrypoints=websecure"
      - "traefik.http.routers.dockge.tls=true"
      - "traefik.http.routers.dockge.tls.certresolver=leresolver"
      - "traefik.http.routers.dockge.middlewares=internal-only@file"
    environment:
      - DOCKGE_STACKS_DIR=/opt/stacks
    networks:
      - proxy

networks:
  proxy:
    external: true